### ISSUE TITLE
为什么用纯代码设置导航栏样式会没有效果？

### ISSUE THREAD

**Issue by HZRZCW** [arcangelw/WZRootNavigationController#1]
#import "LTNavigationBar.h"

@implementation LTNavigationBar

- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        
        self.translucent = NO;
        
        UIColor *bgcolor = [UIColor redColor];
        [self setBarTintColor:bgcolor];
        
        [self setTitleTextAttributes:@{NSFontAttributeName : [UIFont boldSystemFontOfSize:17],NSForegroundColorAttributeName:kColor131d36}];
        [self setTintColor:kColor131d36];
        [self setShadowImage:[UIImage lt_imageWithColor:kColoreff1f5]];
        [self setBackgroundImage:[[UIImage alloc] init] forBarMetrics:UIBarMetricsDefault];
        
    }
    return self;
}

**Comment by arcangelw** [comment]
WZRootNavigationController
   /// 是否转移导航栏属性 默认 ture 使用
    @IBInspectable open var isTransferNavigationBarAttributes:Bool = true
   设置为false

**Comment by HZRZCW** [comment]
我在源码那里直接设置为false后也不行，我现在写一个demo来看看。


------------------ 原始邮件 ------------------
发件人: "ZHE WU"<notifications@github.com>;
发送时间: 2018年7月12日(星期四) 下午5:17
收件人: "arcangelw/WZRootNavigationController"<WZRootNavigationController@noreply.github.com>;
抄送: "张常伟"<708849329@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [arcangelw/WZRootNavigationController] 为什么用纯代码设置导航栏样式会没有效果？ (#1)




WZRootNavigationController
 /// 是否转移导航栏属性 默认 ture 使用
 @IBInspectable open var isTransferNavigationBarAttributes:Bool = true
 设置为false

**Comment by arcangelw** [comment]
develop 分支已经优化完善,请参考demo设置
每个VC的navigationBar完全是独立的，self.wz_navigationController.navigationBar的操作是不对的
直接操作self.navigationController.navigationBar操作就可以
WZ的层级是这样的
WZRootNavigationController (navigationBar 是隐藏的)
 |_> WZContainerController
       |_> WZContainerNavigationController (展示出的独立navigationBar属于这个nav）
        	|_> UIViewController
 |_> WZContainerController
       |_> WZContainerNavigationController
        	|_> UIViewController
 |_> WZContainerController
       |_> WZContainerNavigationController
        	|_> UIViewController
